{% set version = "13.1.1" %}

package:
  name: cuda-libraries
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx or ppc64le]

requirements:
  run:
    - cuda-cudart 13.1.80
    - cuda-nvrtc 13.1.115
    - cuda-opencl 13.1.115    # [linux64 or win]
    - libcublas 13.2.1.1
    - libcufft 12.1.0.78 
    - libcufile 1.16.1.26       # [linux]
    - libcuobjclient 1.0.0.26  # [linux64 or aarch64]
    - libcurand 10.4.1.81
    - libcusolver 12.0.9.81
    - libcusparse 12.7.3.1
    - libnpp 13.0.3.3
    - libnvfatbin 13.1.115
    - libnvjitlink 13.1.115
    - libnvjpeg 13.0.3.75

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library runtime packages.
  description: |
    Meta-package containing all available library runtime packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
