{% set version = "13.3.1" %}

package:
  name: cuda-libraries
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx or ppc64le]

requirements:
  run:
    - cuda-cudart 13.3.29
    - cuda-nvrtc 13.3.33
    - cuda-opencl 13.3.27    # [linux64 or win]
    - libcublas 13.6.0.2
    - libcudla 13.3.29     # [linux and aarch64]
    - libcufft 12.3.0.29
    - libcufile 1.18.1.6       # [linux]
    - libcuobjclient 1.2.0.68  # [linux64 or aarch64]
    - libcurand 10.4.3.29
    - libcusolver 12.2.6.9
    - libcusparse 12.8.2.51
    - libnpp 13.1.2.81
    - libnvfatbin 13.3.29
    - libnvjitlink 13.3.33
    - libnvjpeg 13.2.1.68

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library runtime packages.
  description: |
    Meta-package containing all available library runtime packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
