{% set version = "13.2.1" %}

package:
  name: cuda-libraries
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx or ppc64le]

requirements:
  run:
    - cuda-cudart 13.2.75
    - cuda-nvrtc 13.2.78
    - cuda-opencl 13.2.75    # [linux64 or win]
    - libcublas 13.4.0.1
    - libcudla 13.2.75     # [linux and aarch64]
    - libcufft 12.2.0.46
    - libcufile 1.17.1.22       # [linux]
    - libcuobjclient 1.1.1.22  # [linux64 or aarch64]
    - libcurand 10.4.2.55
    - libcusolver 12.2.0.1
    - libcusparse 12.7.10.1
    - libnpp 13.1.0.48
    - libnvfatbin 13.2.78
    - libnvjitlink 13.2.78
    - libnvjpeg 13.1.0.48

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library runtime packages.
  description: |
    Meta-package containing all available library runtime packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
