{% set version = "13.1.0" %}

package:
  name: cuda-libraries
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx or ppc64le]

requirements:
  run:
    - cuda-cudart 13.1.80
    - cuda-nvrtc 13.1.80
    - cuda-opencl 13.1.80    # [linux64 or win]
    - libcublas 13.2.0.9
    - libcufft 12.1.0.31 
    - libcufile 1.16.0.49       # [linux]
    - libcurand 10.4.1.34
    - libcusolver 12.0.7.41
    - libcusparse 12.7.2.19
    - libnpp 13.0.2.21
    - libnvfatbin 13.1.80
    - libnvjitlink 13.1.80
    - libnvjpeg 13.0.2.28

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library runtime packages.
  description: |
    Meta-package containing all available library runtime packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
