{% set version = "12.8.1" %}

package:
  name: cuda-libraries
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx or ppc64le]

requirements:
  run:
    - cuda-cudart 12.8.90
    - cuda-nvrtc 12.8.93
    - cuda-opencl 12.8.90    # [linux64 or win]
    - libcublas 12.8.4.1
    - libcufft 11.3.3.83 
    - libcufile 1.13.1.3       # [linux]
    - libcurand 10.3.9.90
    - libcusolver 11.7.3.90
    - libcusparse 12.5.8.93
    - libnpp 12.3.3.100
    - libnvfatbin 12.8.90
    - libnvjitlink 12.8.93
    - libnvjpeg 12.3.5.92

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library runtime packages.
  description: |
    Meta-package containing all available library runtime packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
